CREATE TABLE CUSTOMER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BALANCE NUMERIC NOT NULL
);


INSERT INTO CUSTOMER (NAME, BALANCE) VALUES ('pedro', 100.0);
INSERT INTO CUSTOMER (NAME, BALANCE) VALUES ('pablo',  250.0);