# fly.toml file generated for wandering-surf-8416 on 2023-04-17T02:36:48-05:00

app = "wandering-surf-8416"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
